openapi: 3.0.0
info:
  title: API documentation
  version: 1.0.0
servers:
  - url: https://sandbox.musement.com/api/v3
tags:
  - name: Forecast
paths:
  /cities/{id}/forecast:
    $ref: './resources/forecast.yaml#/Forecast'
  /cities/{id}/forecast/{day}:
    $ref: './resources/forecast.yaml#/ForecastByDay'

components:
  securitySchemes:
    BearerAuth:
      $ref: './schemas/security_schema.yaml'